export const Dependencies = {
  CONFIGURATION: "CONFIGURATION",
  NODE_MANAGER: "NODE_MANAGER",
  DISTRIBUTOR: "DISTRIBUTOR",
  SESSION_MANAGER: "SESSION_MANAGER",
  SOCKET_HUB_NAMESPACE: "SOCKET_HUB_NAMESPACE",
  SOCKET_STREAM_NAMESPACE: "SOCKET_STREAM_NAMESPACE",
  SOCKET_WEB_CLIENT_NAMESPACE: "SOCKET_WEB_CLIENT_NAMESPACE",
};
