export const Dependencies = {
  CONFIGURATION: "CONFIGURATION",
  ADB: "ADB",
  PLUGIN_EVENT_EMITTER: "PLUGIN_EVENT_EMITTER",
  SOCKET_EVENT_EMITTER: "SOCKET_EVENT_EMITTER",
  DEVICE_TRACKER: "DEVICE_TRACKER",
  DEVICE_MANAGER: "DEVICE_MANAGER",
  REMOTE_DEVICE_CONTROL_MANAGER: "REMOTE_DEVICE_CONTROL_MANAGER",
  PROXY_WEBDRIVER: "PROXY_WEBDRIVER",
};

export const PluginEvents = {
  APPIUM_SERVER_STARTED: "APPIUM_SERVER_STARTED",
  REGISTER_NODE: "REGISTER_NODE",
  SOCKET_RECONNECTED: "SOCKET_RECONNECTED",
  DEVICE_CONNECTED: "DEVICE_CONNECTED",
  DEVICE_DICONNECTED: "DEVICE_DICONNECTED",
  BLOCK_DEVICE: "BLOCK_DEVICE",
  UNBLOCK_DEVICE: "UNBLOCK_DEVICE",
  NEW_SESSION: "NEW_SESSION",
  PROCESS_KILLED: "PROCESS_KILLED",
};

export const SocketEvents = {
  NODE_REGISTERED: "NODE_REGISTERED",
};
